apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  environment: {{ .Values.configMap.environment }}
  managed_by: {{ .Values.configMap.managed_by }}
